version: '2'

services:
  backend:
    build:
      context: ./backend/
    volumes:
      - ./backend/:/usr/app
      - backend_node_modules:/usr/app/node_modules
    ports:
      - "6000:6000"
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DB_HOST: '${DB_HOST}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      SESSION_SECRET: '${SESSION_SECRET}'
      NODE_ENV: 'development'      
    depends_on:
      - db
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend/
    command: npm start
    stdin_open: 'true'
    tty: 'true'
    volumes:
      - ./frontend/:/usr/app
      - frontend_node_modules:/usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
  redis:
    restart: unless-stopped
    image: redis:6-alpine
    command: --requirepass ${REDIS_PASSWORD}
    expose:
      - '${REDIS_PORT}'
    env_file:
      - .env
    networks:
      - app-network
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules: